# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7z010clg400-1
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ipshared/ec67/hdl {
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/interface/axi4_if.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/axi4_slave.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/interface/gpio_if.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/red_pitaya_dfilt1.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_pdm.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/red_pitaya_pll.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/prj/v0.94/rtl/red_pitaya_ps.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/interface/sys_bus_if.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/sys_bus_interconnect.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/sys_bus_stub.sv
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/prj/v0.94/rtl/red_pitaya_top.sv
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ipshared/ec67/hdl {
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/realtime/system_axi_protocol_converter_0_0_stub.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/realtime/system_proc_sys_reset_0_stub.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/realtime/system_processing_system7_0_stub.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/realtime/system_xadc_0_stub.v
      c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ipshared/fcfc/hdl/xlconstant_v1_1_vl_rfs.v
      c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xlconstant_0/synth/system_xlconstant_0.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/synth/system.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/axi_master.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/axi_wr_fifo.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/divide.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_ams.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_asg.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_asg_ch.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_daisy.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_daisy_rx.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_daisy_test.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_daisy_tx.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_hk.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_pid.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_pid_block.v
      C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/imports/ReferenceTest/rtl/classic/red_pitaya_scope.v
    }
      rt::read_vhdl -lib xpm C:/Xilinx/Vivado/2020.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top red_pitaya_top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "C:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/.Xil/Vivado-9636-DESKTOP-UF70E69/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
