# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xci
# IP: The module: 'system_xadc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xadc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xadc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xci
# IP: The module: 'system_xadc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xadc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/Ian/Desktop/OIST/RedPitaya/ReferenceTest/prj/v0.94/project/redpitaya.srcs/sources_1/bd/system/ip/system_xadc_0/system_xadc_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_xadc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
